const state={hour:8,day:4,weather:'sunny',harmony:32,inventory:{'Fairy Mint':0,'Forest Berries':0,'Star Mushroom':0,'Wild Honey':0},plots:[{type:'empty'},{type:'growing',growth:1,watered:false},{type:'weeds'}],memory:false,tool:'hand'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const game=$('#game'), toast=$('#toast');
function say(message){toast.textContent=message;toast.classList.add('show');clearTimeout(say.timer);say.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
function addHarmony(n,reason){state.harmony=Math.min(100,state.harmony+n);$('#harmonyValue').textContent=state.harmony;$('#harmonyBar').style.width=state.harmony+'%';say(`${reason}  +${n} Harmony ✦`);if(state.harmony>=50&&state.harmony-n<50)setTimeout(()=>say('Forest path unlocked at 50 Harmony!'),2300)}
function updateInventory(){const ids={'Fairy Mint':'invMint','Forest Berries':'invBerry','Star Mushroom':'invMushroom','Wild Honey':'invHoney'};Object.entries(ids).forEach(([k,id])=>$('#'+id).textContent=state.inventory[k]);$('#mintProgress').textContent=`${Math.min(3,state.inventory['Fairy Mint'])} / 3`;const ready=state.inventory['Fairy Mint']>=3;$('#giveMint').disabled=!ready;$('#giveMint').textContent=ready?'Give mint to Juniper':'Gather 3 Fairy Mint'}
function updateTime(){const night=state.hour>=18||state.hour<6;game.classList.toggle('night',night);game.classList.toggle('day',!night);const suffix=state.hour>=12?'PM':'AM', h=state.hour%12||12;$('#clock').textContent=`${h}:10 ${suffix}`;$('#dayLabel').textContent=`DAY ${state.day} · ${night?'NIGHT':state.hour<12?'MORNING':'AFTERNOON'}`}
$('#timeButton').addEventListener('click',()=>{state.hour=(state.hour+4)%24;if(state.hour<4)state.day++;state.plots.forEach(p=>{if(p.type==='growing'&&p.watered){p.growth=Math.min(3,p.growth+(state.weather==='rainy'?2:1));p.watered=false}});$$('.gather.used').forEach(x=>x.classList.remove('used'));updateTime();renderPlots();say('Time drifts softly through the garden…')});
const weatherCycle=[['sunny','☀️','Sunny'],['rainy','🌧️','Rainy · plants grow faster'],['foggy','🌫️','Foggy · rare creatures visit']];
$('#weatherButton').addEventListener('click',()=>{let i=weatherCycle.findIndex(x=>x[0]===state.weather);const next=weatherCycle[(i+1)%3];game.classList.remove(state.weather);state.weather=next[0];game.classList.add(state.weather);$('#weatherButton').textContent=next[1];say(next[2]);if(next[0]==='rainy')state.plots.filter(p=>p.type==='growing').forEach(p=>p.watered=true)});
$$('.gather').forEach(el=>el.addEventListener('click',()=>{if(el.classList.contains('used'))return say('This patch needs time to regrow.');const item=el.dataset.item;state.inventory[item]++;el.classList.add('used');el.style.opacity=.25;setTimeout(()=>el.style.opacity='',350);updateInventory();say(`${el.dataset.icon}  ${item} gathered`)}));
function openModal(id){const modal=$('#'+id);modal.hidden=false;modal.classList.remove('closing');modal.classList.add('opening');setTimeout(()=>modal.classList.remove('opening'),350)}function closeModal(id){const modal=$('#'+id);if(id==='instructionsModal'){modal.classList.add('closing');setTimeout(()=>{modal.hidden=true;modal.classList.remove('closing')},220)}else modal.hidden=true}
$('#mapButton').onclick=()=>openModal('mapModal');$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.map-grid button:not(.current)').forEach(b=>b.onclick=()=>say(`${b.querySelector('strong').textContent} is ready for the full game transition.`));
$('#instructionsButton').onclick=()=>openModal('instructionsModal');
$('#memorySpot').onclick=()=>{if(state.memory)return say('You already found this memory fragment.');state.memory=true;openModal('memoryModal');$('#memorySpot').style.display='none';addHarmony(5,'A memory stirs.')};
$('#foxButton').onclick=()=>{const q=$('#questCard');q.style.display='block';say('Juniper: “The mint here works wonders, you know.”')};$('#collapseQuest').onclick=()=>$('#questCard').style.display='none';
$('#giveMint').onclick=()=>{state.inventory['Fairy Mint']-=3;updateInventory();$('#questCard').innerHTML='<small>REQUEST COMPLETE</small><div class="quest-head"><span>🦊</span><div><strong>Juniper is delighted!</strong><p>New recipe: Moonmint Tea</p></div></div><div class="quest-progress"><span>Reward</span><b>📜 Recipe</b></div>';addHarmony(12,'Creature helped!')};
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool;if(state.tool==='decorate')openModal('decorModal')});
let activePlot=0;
function renderPlots(){const labels={empty:['· · ·','Empty plot'],weeds:['〽','Needs weeding']};$$('.plot').forEach((el,i)=>{const p=state.plots[i];el.className='plot '+(p.type==='growing'?'planted':p.type==='weeds'?'weeded':'');if(p.type==='growing'){const icons=['·','♧','♣','🌿'];el.innerHTML=`<span class="sprout">${icons[p.growth]}</span><small>Fairy Mint · ${p.growth}/3${p.watered?' · watered':''}</small>`}else el.innerHTML=`<span>${labels[p.type][0]}</span><small>${labels[p.type][1]}</small>`})}
$$('.plot').forEach(el=>el.onclick=()=>{activePlot=+el.dataset.plot;renderPlotModal();openModal('plotModal')});
function renderPlotModal(){const p=state.plots[activePlot], actions=$('#plotActions');actions.innerHTML='';const add=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;actions.appendChild(b)};if(p.type==='empty'){$('#plotIcon').textContent='◉';$('#plotTitle').textContent='Empty soil';$('#plotDescription').textContent='Plant a Fairy Mint seed here.';add('Plant seed',()=>{p.type='growing';p.growth=0;p.watered=false;closeModal('plotModal');renderPlots();addHarmony(2,'A seed was planted.')})}else if(p.type==='weeds'){$('#plotIcon').textContent='🌾';$('#plotTitle').textContent='A weedy patch';$('#plotDescription').textContent='Clear the weeds to make room for something lovely.';add('Pull weeds',()=>{p.type='empty';closeModal('plotModal');renderPlots();addHarmony(3,'The garden feels tidier.')})}else if(p.growth>=3){$('#plotIcon').textContent='🌿';$('#plotTitle').textContent='Fairy Mint is ready!';$('#plotDescription').textContent='Its leaves smell like cool starlight.';add('Harvest',()=>{state.inventory['Fairy Mint']+=2;p.type='empty';updateInventory();closeModal('plotModal');renderPlots();addHarmony(2,'Fairy Mint harvested.')})}else{$('#plotIcon').textContent=p.watered?'💧':'🌱';$('#plotTitle').textContent=p.watered?'Watered Fairy Mint':'Growing Fairy Mint';$('#plotDescription').textContent=`Growth stage ${p.growth} of 3. Let time pass after watering.`;if(!p.watered)add('Water plant',()=>{p.watered=true;closeModal('plotModal');renderPlots();addHarmony(2,'The plant drinks happily.')});add('Wait 4 hours',()=>{closeModal('plotModal');$('#timeButton').click()})}}
$$('[data-decor]').forEach(b=>b.onclick=()=>{const d=document.createElement('span');d.className='placed-decor';d.textContent=b.dataset.decor;d.style.left=(47+Math.random()*34)+'%';d.style.top=(42+Math.random()*30)+'%';$('#scene').appendChild(d);closeModal('decorModal');addHarmony(3,'The garden grew cozier.')});
updateTime();updateInventory();renderPlots();
